# Merge PR if all checks pass

name: DependaBotMerge

on:
  pull_request_target:

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}